"""Initial migration

Revision ID: 97c39cae2bcb
Revises:
Create Date: 2025-05-05 17:16:40.677446

"""
# pyright: reportUnusedCallResult=false

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97c39cae2bcb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("source", sa.Enum("SAMMGOV", name="scrapingsource"), nullable=False),
        sa.Column("run_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "opportunity_scrapes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("opportunity_run_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_run_id"],
            ["opportunity_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_scrapes")
    op.drop_table("opportunity_run")
    # ### end Alembic commands ###
