services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - venv:/workspace/.venv
      - uv-cache:/home/vscode/.cache/uv
    command: sleep infinity
    environment:
      UV_LINK_MODE: copy
      PYTHONBREAKPOINT: rfp_scraper.debug.enhanced_breakpoint.set_trace
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zbids
volumes:
  venv:
  uv-cache:
